
name: "📝 Documents"
description: "문서 작성 또는 수정 작업"
title: "[Docs] "
labels:
  - documentation

body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 작성하거나 수정할 문서 내용을 간단히 작성
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: 완료 조건
      description: 문서 작업의 완료 기준을 작성
      placeholder: |
        - [ ] 문서 작성 또는 수정 완료
        - [ ] 내용 검토 완료
    validations:
      required: true