name: "✨ Feature"
description: "새로운 기능 또는 작업"
title: "[Feature] "
labels:
  - feature
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 구현하거나 추가할 내용을 간단히 작성
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: 완료 조건
      description: 이 작업이 완료되었다고 판단할 수 있는 기준을 작성
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
    validations:
      required: true